version: '2'
services:
  rabbit:
    image: rabbitmq:management
    container_name: rabbit 
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      - ../../conf/rabbit/plugins:/plugins/my
      - ../../conf/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      # 配置rabbit插件扫描文件夹
      - RABBITMQ_PLUGINS_DIR=/plugins:/plugins/my
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test

