version: '2'
services:
  mongo: 
    image: mongo
    container_name: mongo
    environment
      - TZ=Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ../../data/mongo/rep1/data:/data/db
      - ../../data/mongo/rep1/bak:/data/bak
#      - /etc/localtime:/etc/localtime
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      - TZ=Asia/Shanghai
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example





