version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      TZ: Asia/Shanghai
      KAFKA_ADVERTISED_HOST_NAME: 192.168.31.55
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_BROKER_ID: "1"
      KAFKA_ADVERTISED_PORT: 9092
  zk:
    image: zookeeper
    container_name: kafka-zk