version: '2'  
services:
    kibana:   
        image: kibana  
        container_name: kibana  
        ports:  
           - "5601:5601"  
        links:  
           - elasticsearch:elasticsearch 
        environment:
           - TZ=Asia/Shanghai






