version: '2'
services:
  tomcat:
    image: ueditor.baidu.tomcat
    container_name: ueditor
    volumes:
      - ../../conf/ueditor/OSSKey.properties:/usr/local/tomcat/webapps/ueditor/WEB-INF/classes/OSSKey.properties
    ports:
      - "8888:8080"
    environment:
      - TZ=Asia/Shanghai
