version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    # volumes:
    #   - ../../data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #   - ../../data/nginx/conf/conf.d:/etc/nginx/conf.d
    #   - ../../project:/project:ro
    #   - ../../data/certbot/letsencrypt/archive:/ssl
    # ports:
    #   - "80:80"
    #   - "443:443"
    networks:
      app_net:
        ipv4_address: 10.10.1.34
networks:
  app_net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: 10.10.1.0/24
        gateway: 10.10.1.1