version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
#      - /etc/localtime:/etc/localtime
      - ../../data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ../../html:/html:ro
      - ../../data/certbot/letsencrypt/archive:/ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
