version: '3.1'
services:
  mysql:
    image: mysql:8.0.15
    container_name: mysql
    volumes:
      - ../../conf/mysql/conf:/etc/mysql/conf.d
      - ../../data/mysql/data:/var/lib/mysql
      - ../../data/mysql/log:/var/log/mysql
      - ../../data/mysql/bak:/bak
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
