version: "2"
services:
  # 问题排查 https://docs.qq.com/doc/BibfIy26LF8B31cHKf3v6aDZ2uFEkR244JS01IQmKC2Cjyb92WXZOz2PNoNJ4SSq071Y681J2?tdsourcetag=s_macqq_grpfile
  # https://github.com/pjialin/py12306
  py12306:
    image: pjialin/py12306
    container_name: py12306
    volumes:
      - ../../conf/py12306/env.py:/config/env.py
      - ../../conf/py12306/api.py:/code/py12306/helpers/api.py
      # - ../../data/py12306/12306.log:/config/12306.log
      - ../../data/py12306:/data
    ports:
      - "8008:8008"
    links:
      - ocr12306
    environment:
      - API_FREE_CODE_QCR_API=http://ocr12306/check/

  # https://github.com/pjialin/12306-ocr
  # https://py12306-helper.pjialin.com/
  ocr12306:
    image: pjialin/12306-ocr
    container_name: ocr12306

